In [1]:
import altair as alt
import pandas as pd

In [4]:
df_listed = pd.read_csv('species-listings-by-year-totals-report.csv')

df_listed

    Calendar Year  Number of Species Listings
0            2024                           3
1            2023                          26
2            2022                           7
3            2021                          10
4            2020                           4
5            2019                           4
6            2018                           5
7            2017                           9
8            2016                          73
9            2015                          27
10           2014                          36
11           2013                          83
12           2012                          44
13           2011                          11
14           2010                          54
15           2009                           6
16           2008                           2
17           2006                          12
18           2005                           7
19           2004                           8
20           2003                           2
21           2002                          11
22           2001                          10
23           2000                          40
24           1999                          23
25           1998                          56
26           1997                          78
27           1996                          91
28           1995                          18
29           1994                         128
30           1993                          67
31           1992                          79
32           1991                          80
33           1990                          38
34           1989                          32
35           1988                          47
36           1987                          60
37           1986                          36
38           1985                          59
39           1984                          32
40           1983                           7
41           1982                          11
42           1981                           4
43           1980                          16
44           1979                          37
45           1978                          42
46           1977                          21
47           1976                          35
48           1975                          11
49           1973                           7
50           1972                           3
51           1970                          44
52           1967                          70
53           1968                           0
54           1969                           0
55           1971                           0
56           1974                           0
57           2007                           0

In [5]:
alt.Chart(data=df_listed).mark_line(point=True).encode(
    x="Calendar Year:N",
    y=alt.Y("Number of Species Listings:Q", scale=alt.Scale(zero=False))
)

alt.Chart(...)